import express from "express";
import userController from "../controller/users.js";
import cloudinary from "../database/cloudinary.js";
const userRouter = express.Router();
userRouter.get("/", userController.findAll);
userRouter.get("/userslike/:postid", userController.getUsersLike);
userRouter.get("/find/:id", userController.findById);
userRouter.post("/findlist", userController.getUsersByListId);
userRouter.get("/except/:id", userController.findExceptId);
userRouter.delete("/:id"), userRouter.put("/:id");
userRouter.post("/uploadavatar/:userid", userController.uploadAvatar);
userRouter.get("/find_by_username/:username", userController.findByUsername);
userRouter.post("/follow", userController.getFollowing);
export default userRouter;
